### ISSUE TITLE
Invalid part number '2' while decoding message type 24

### ISSUE THREAD

**Issue by KylePallo** [mjaros/ais-decoder#15]
I'm experiencing an issue when parsing high volume satellite AIS data where the below error is being thrown:
`Invalid part number '2' while decoding message type 24`

This does appear to be relatively rare (maybe every million records I've receiving), but it seems to destroy the stream and there doesn't seem to be anything I can do to handle the error from my side (i.e. log and skip) as I'm receiving the following afterwards:
`[ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed`

I'm aware part number should alway be 0 or 1, but unfortunately there isn't anything I can do about a faulty transmitter.

I've simply moved the `switch` and `if` statements in [ais-decoder.ts](https://github.com/mjaros/ais-decoder/blob/bd0ba347acff1bcc24b09891e5b3a9228d072039/src/ais-decoder.ts#L93) into a try/catch to prevent destroying the stream but I figured I'd open an issue incase you have a more elegant solution or a reason to destroy the stream on this event.

**Comment by KylePallo** [comment]
Attaching the stack trace from the most recent error now that it's being caught in a try:
`DecodingError: Invalid part number '3' while decoding message type 24
    at new AisMessage24 (/Users/kylepallo/Git/ais/node_modules/ais-stream-decoder/dist/messages/ais-message-24.js:21:19)`
`    at AisDecoder.decodePayload (/Users/kylepallo/Git/ais/node_modules/ais-stream-decoder/dist/ais-decoder.js:82:38)`
`    at AisDecoder._transform (/Users/kylepallo/Git/ais/node_modules/ais-stream-decoder/dist/ais-decoder.js:34:22)`
`    at AisDecoder.Transform._write (node:internal/streams/transform:184:23)`
`    at writeOrBuffer (node:internal/streams/writable:390:12)`
`    at _write (node:internal/streams/writable:331:10)`
`    at AisDecoder.Writable.write (node:internal/streams/writable:335:10)`
`    at processMessage (/Users/kylepallo/Git/ais/dist/index.js:83:20)`
`    at WebSocket.<anonymous> (/Users/kylepallo/Git/ais/dist/index.js:115:13)`
`    at WebSocket.emit (node:events:526:28)`
